raw_data_path: "data/raw_data.csv"
preprocess_data_path: "data/preprocess_data.csv"
label2id_path: "data/label2id.json"
id2label_path: "data/id2label.json"
hugging_face_model_path: "bert-base-uncased"
classification_report_path: "data/classification_report.txt"
model_save_path: "data/model"
tokenizer_save_path: "data/tokenizer"
max_length: 128
train_batch_size: 128
valid_batch_size: 128
epochs: 1
learning_rate: 0.00001
max_gradient_norm: 10
df_sample_size: 0.001
train_size: 0.8
seed: 23
