name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ner-model/
          file: ner-model/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_ner_app:latest
